import { CKEditor } from "@ckeditor/ckeditor5-react";
import {
  ClassicEditor,
  Autosave,
  Essentials,
  Paragraph,
  Bold,
  Italic,
  Link,
  AutoLink,
  Fullscreen,
  Underline,
  Strikethrough,
  Code,
  Subscript,
  Superscript,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  Highlight,
  BlockQuote,
  Heading,
  CodeBlock,
  Indent,
  IndentBlock,
  Alignment,
  Style,
  GeneralHtmlSupport,
  List,
  TodoList,
  Table,
  TableToolbar,
  TableCaption,
  SourceEditing,
  HtmlComment,
} from "ckeditor5";
import "ckeditor5/ckeditor5.css";

const LICENSE_KEY = "GPL";

export default function TextEditorClient({
  value = "",
  onChange,
  placeholder,
  configExtras = {},
}) {
  const editorConfig = {
    toolbar: {
      items: [
        "undo",
        "redo",
        "|",
        "sourceEditing",
        "fullscreen",
        "|",
        "heading",
        "|",
        "fontSize",
        "fontFamily",
        "fontColor",
        "fontBackgroundColor",
        "|",
        "bold",
        "italic",
        "underline",
        "strikethrough",
        "subscript",
        "superscript",
        "code",
        "|",
        "link",
        "insertTable",
        "highlight",
        "blockQuote",
        "codeBlock",
        "|",
        "alignment",
        "|",
        "bulletedList",
        "numberedList",
        "todoList",
        "outdent",
        "indent",
      ],
      shouldNotGroupWhenFull: false,
    },
    plugins: [
      Alignment,
      AutoLink,
      Autosave,
      BlockQuote,
      Bold,
      Code,
      CodeBlock,
      Essentials,
      FontBackgroundColor,
      FontColor,
      FontFamily,
      FontSize,
      Fullscreen,
      GeneralHtmlSupport,
      Heading,
      Highlight,
      HtmlComment,
      Indent,
      IndentBlock,
      Italic,
      Link,
      List,
      Paragraph,
      SourceEditing,
      Strikethrough,
      Style,
      Subscript,
      Superscript,
      Table,
      TableCaption,
      TableToolbar,
      TodoList,
      Underline,
    ],
    fontFamily: { supportAllValues: true },
    heading: {
      options: [
        {
          model: "paragraph",
          title: "Paragraph",
          class: "ck-heading_paragraph",
        },
        {
          model: "heading1",
          view: "h1",
          title: "Heading 1",
          class: "ck-heading_heading1",
        },
        {
          model: "heading2",
          view: "h2",
          title: "Heading 2",
          class: "ck-heading_heading2",
        },
        {
          model: "heading3",
          view: "h3",
          title: "Heading 3",
          class: "ck-heading_heading3",
        },
        {
          model: "heading4",
          view: "h4",
          title: "Heading 4",
          class: "ck-heading_heading4",
        },
        {
          model: "heading5",
          view: "h5",
          title: "Heading 5",
          class: "ck-heading_heading5",
        },
        {
          model: "heading6",
          view: "h6",
          title: "Heading 6",
          class: "ck-heading_heading6",
        },
      ],
    },
    fontSize: {
      options: [10, 12, 14, "default", 18, 20, 22],
      supportAllValues: true,
    },
    licenseKey: LICENSE_KEY,
    placeholder: placeholder || "Type or paste your content here…",
    htmlSupport: {
      allow: [{ name: /^.*$/, styles: true, attributes: true, classes: true }],
    },
    link: {
      addTargetToExternalLinks: true,
      defaultProtocol: "https://",
    },
    ...configExtras,
  };

  return (
    <CKEditor
      editor={ClassicEditor}
      config={editorConfig}
      data={value}
      onChange={(_, editor) => onChange?.(editor.getData())}
    />
  );
}
